### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by svandragt** [r0x0r/traktorlibrarian#8]
Hi I just installed Traktor Librarian on High Sierra and on startup it fails. Anything I can do or does it not work with the latest MacOS? It's system python version is 2.7.10 if that matters.

![screen shot 2018-02-03 at 14 51 55](https://user-images.githubusercontent.com/594871/35768317-d644877e-08f1-11e8-8dd1-f6a595f5c5e2.png)

```
default	14:49:38.847614 +0000	Traktor Librarian	Error in sys.excepthook:
default	14:49:38.847654 +0000	Traktor Librarian	TypeError: _exception_hook() takes exactly 4 arguments (3 given)
default	14:49:38.847679 +0000	Traktor Librarian	
default	14:49:38.847702 +0000	Traktor Librarian	Original exception was:
default	14:49:38.847723 +0000	Traktor Librarian	Traceback (most recent call last):
default	14:49:38.847745 +0000	Traktor Librarian	  File "/private/var/folders/n7/xvxl1vlx2jg0_h3qxdt79r6h0000gn/T/AppTranslocation/A52FD0CC-E00D-4707-AB91-B5618708BF68/d/Traktor Librarian.app/Contents/Resources/__boot__.py", line 77, in <module>
default	14:49:38.847771 +0000	Traktor Librarian	    _run()
default	14:49:38.847793 +0000	Traktor Librarian	  File "/private/var/folders/n7/xvxl1vlx2jg0_h3qxdt79r6h0000gn/T/AppTranslocation/A52FD0CC-E00D-4707-AB91-B5618708BF68/d/Traktor Librarian.app/Contents/Resources/__boot__.py", line 62, in _run
default	14:49:38.847814 +0000	Traktor Librarian	    exec(compile(source, path, 'exec'), globals(), globals())
default	14:49:38.847835 +0000	Traktor Librarian	  File "/private/var/folders/n7/xvxl1vlx2jg0_h3qxdt79r6h0000gn/T/AppTranslocation/A52FD0CC-E00D-4707-AB91-B5618708BF68/d/Traktor Librarian.app/Contents/Resources/Traktor Librarian.py", line 14, in <module>
default	14:49:38.847859 +0000	Traktor Librarian	    from guiserver import start_webserver
default	14:49:38.847879 +0000	Traktor Librarian	  File "guiserver.pyc", line 3, in <module>
default	14:49:38.847924 +0000	Traktor Librarian	  File "librarian.pyc", line 17, in <module>
default	14:49:38.847970 +0000	Traktor Librarian	  File "clean.pyc", line 10, in <module>
default	14:49:38.848109 +0000	Traktor Librarian	  File "logger.pyc", line 40, in get_logger
default	14:49:38.848137 +0000	Traktor Librarian	  File "logging/__init__.pyc", line 913, in __init__
default	14:49:38.848294 +0000	Traktor Librarian	  File "logging/__init__.pyc", line 943, in _open
default	14:49:38.848320 +0000	Traktor Librarian	IOError: [Errno 30] Read-only file system: '/private/var/folders/n7/xvxl1vlx2jg0_h3qxdt79r6h0000gn/T/AppTranslocation/A52FD0CC-E00D-4707-AB91-B5618708BF68/d/Traktor Librarian.app/Contents/Resources/log.txt'
default	14:49:38.915170 +0000	Traktor Librarian	2018-02-03 14:49:38.914 Traktor Librarian[89588:8806007] Traktor Librarian Error
```
I don't have anything else running on that port locally.

**Comment by r0x0r** [comment]
Hello Sander,

It looks like you are running it from a downloaded location. Try moving the
app to /Applications, it should work from there.
Sierra introduced new security measures, which prevent apps from running in
random locations.


Cheers,
Roman

**Comment by svandragt** [comment]
I was running Traktor Librarian from /Applications/. Moving it to ~/Applications/ solved the problem.  It's probably because my user is not an administrator user.
